export const CHOOSE_TABLE = 'CHOOSE_TABLE';

export const PLUS_MENU_POSITION_COUNT = 'PLUS_MENU_POSITION_COUNT';
export const MINUS_MENU_POSITION_COUNT = 'MINUS_MENU_POSITION_COUNT';
export const INITIALIZE_MENU_POSITIONS = 'INITIALIZE_MENU_POSITIONS';
export const SWITCH_TIP = 'SWITCH_TIP';
export const CHANGE_ID = 'CHANGE_ID';

export const SET_PAYMENT_URI = 'SET_PAYMENT_URI';
export const UPDATE_TRANSACTION_STATUS = 'UPDATE_TRANSACTION_STATUS';

export const CHOOSE_SCREEN = 'CHOOSE_SCREEN';




